#!/bin/bash
system=`uname -a`
if [[ "$system" =~ "Linux" || $system =~ "AppleTV" ]]; then
	printf 'linux'
	exit 0
fi
if [[ $system =~ "Darwin" && ! $system =~ "AppleTV" ]]; then
	printf 'osx'
	exit 0
fi
if [[ $system =~ "FreeBSD" ]]; then
	printf 'freebsd'
	exit 0
fi
if [[ $system == "MINGW32_NT-6.1" ]]; then
	printf 'mingw'
	exit 0
fi

printf 'Unknown system' >&2
exit 1
