#!/bin/zsh
alias status='git status -s'
alias commit='git commit -a'
alias gadd='git add .'
alias push='git push origin --all'
alias pull='git pull origin master'
alias mis='cat'
alias canhaz='sudo apt-get install'
alias grep='grep -Hn'
