#!/bin/zsh
alias status='git status -s'
alias commit='git commit'

alias ls='ls -h'
alias l='ls -CF'
alias ll='ls -l'
alias la='ls -al'
alias mis='cat'

if [ "$system" == 'Linux' ]; then
	rm='rm -I'
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
	eval "`dircolors -b`"
	alias ls='ls --color=auto'
	
	alias grep='grep --color=auto'
	alias egrep='egrep --color=auto'
	alias fgrep='fgrep --color=auto'
fi
