#!/bin/zsh
system=`uname`

DOTFILES=$(dirname $(dirname $_))

if [ -f ~/.localenv ]; then
	. ~/.localenv
fi

if [[ -z "$LANG" ]]; then
	export LANG='en_US.UTF-8'
fi

if [[ -e ~/.oh-my-zsh/oh-my-zsh.sh ]] then
	export ZSH=$HOME/.oh-my-zsh
	if [[ -z "$ZSH_THEME" ]] then
		export ZSH_THEME="jreese"
	fi
	if [[ $system == 'Linux' ]]; then
		plugins=(git github svn)
	fi
	if [[ $system == 'Darwin' ]]; then
		plugins=(git github svn osx)
	fi
	. ~/.oh-my-zsh/oh-my-zsh.sh
	unsetopt correct_all
	# Disable the automatic titling, it screws up tmux
	DISABLE_AUTO_TITLE=true
fi

if [[ $system == 'Linux' ]]; then
	. $DOTFILES/zsh/rc.linux
fi
if [[ $system == 'Darwin' ]]; then
	. $DOTFILES/zsh/rc.osx
fi

. $DOTFILES/aliases

if [[ -f ~/.dir_colors && ( -x /usr/local/bin/dircolors || -x /usr/bin/dircolors ) ]]; then
    eval `dircolors ~/.dir_colors`
fi

if [[ -e ~/.ssh/ssh_auth_sock ]] then
	export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
fi

unset DOTFILES
unset system
