#!/bin/zsh
system=`uname`

DOTFILES=$(dirname $(dirname $_))

if [ -f ~/.localenv ]; then
	. ~/.localenv
fi

if [[ $system == 'Linux' ]]; then
	. $DOTFILES/zsh/environment.linux
	. $DOTFILES/zsh/rc.linux
fi
if [[ $system == 'Darwin' ]]; then
	. $DOTFILES/zsh/environment.osx
	. $DOTFILES/zsh/rc.osx
fi

if [[ -e ~/.oh-my-zsh/oh-my-zsh.sh ]] then
	export ZSH=$HOME/.oh-my-zsh
	export ZSH_THEME="jreese"
	if [[ $system == 'Linux' ]]; then
		plugins=(git github svn)
	fi
	if [[ $system == 'Darwin' ]]; then
		plugins=(git github svn osx)
	fi
	. ~/.oh-my-zsh/oh-my-zsh.sh
	unsetopt correct_all
fi

. $DOTFILES/zsh/aliases

if [[ -f ~/.dir_colors && -x /usr/local/bin/dircolors ]]; then
    eval `dircolors ~/.dir_colors`
fi

unset DOTFILES
unset system
