#!/bin/bash
alias status='git status -s'
alias commit='git commit'
alias push='git push origin master'

alias l='ls -CFh'
alias ll='ls -lh'
alias la='ls -alh'
alias mis='cat'
alias canhaz='sudo apt-get install'

if [ "$system" == 'Linux' ]; then
	alias rm='rm -I'
fi

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
	eval "`dircolors -b`"
	alias ls='ls --color=auto'
	
	alias grep='grep --color=auto'
	alias egrep='egrep --color=auto'
	alias fgrep='fgrep --color=auto'
fi
