#!/bin/bash
rcfiles=$(dirname ${BASH_ARGV[0]%/*})

system=`$rcfiles/system`

if [ -f ~/.localenv ]; then
	. ~/.localenv
fi

. $rcfiles/bash/colors

if [ "$system" == 'Linux' ]; then
	. $rcfiles/bash/rc.linux
fi
if [ "$system" == 'OSX' ]; then
	. $rcfiles/bash/rc.osx
fi
if [ "$system" == 'MinGW' ]; then
	. $rcfiles/bash/rc.mingw
fi

if [ ! -n "$HOSTNAME" ]; then
	HOSTNAME=`hostname -s`
fi

. $rcfiles/aliases
. $rcfiles/bash/completion
. $rcfiles/tools

if [[ -f ~/.dir_colors && ( -x /usr/local/bin/dircolors || -x /usr/bin/dircolors ) ]]; then
    eval `dircolors ~/.dir_colors`
fi

if [[ -e ~/.ssh/ssh_auth_sock ]]; then
    export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
fi

unset rcfiles
unset system
