#!/bin/bash
rcfiles=$HOME/.homesick/repos/rc-files

system=$($rcfiles/system)

if [[ -f $HOME/.custom ]]; then
	source $HOME/.custom
fi

if [[ -f $HOME/.localenv ]]; then
	source $HOME/.localenv
fi

# homeshick stuff
source "$HOME/.homesick/repos/homeshick/homeshick.sh"
# Check if castles need refreshing
homeshick --quiet refresh 56 $HOMESHICK_REFRESH_REPOS
unset HOMESHICK_REFRESH_REPOS

source "$rcfiles/bash/colors"

if [[ -f "$HOME/.homesick/repos/rc-files/zsh/rc.$system.zsh" ]]; then
  source "$HOME/.homesick/repos/rc-files/zsh/rc.$system.zsh"
fi

source "$HOME/.homesick/repos/homeshick/completions/homeshick-completion.bash"
source "$rcfiles/bash/completion"

if [[ ! -n "$HOSTNAME" ]]; then
	HOSTNAME=$(hostname -s)
fi

if [[ -f $HOME/.dir_colors && ( -x /usr/local/bin/dircolors || -x /usr/bin/dircolors ) ]]; then
    eval "$(dircolors $HOME/.dir_colors)"
fi

ls -A /etc/profile.d 2>/dev/null | grep '' >/dev/null
if $?; then
  for i in /etc/profile.d/*.sh; do
    [[ -r $i ]] && . "$i"
  done
  unset i
fi

unset rcfiles
unset system
