#!/bin/bash
rcfiles=$HOME/.homesick/repos/rc-files

system=$($rcfiles/system)

if [[ -f $HOME/.custom ]]; then
	source $HOME/.custom
fi

if [[ -f $HOME/.localenv ]]; then
	source $HOME/.localenv
fi

# homeshick stuff
source "$HOME/.homesick/repos/homeshick/homeshick.sh"
# Check if castles need refreshing
homeshick --quiet refresh 56 $HOMESHICK_REFRESH_REPOS
unset HOMESHICK_REFRESH_REPOS
source "$HOME/.homesick/repos/homeshick/completions/homeshick-completion.bash"

source "$rcfiles/bash/colors"

if [[ "$system" == 'Linux' ]]; then
	source "$rcfiles/bash/rc.linux"
fi
if [[ "$system" == 'FreeBSD' ]]; then
	source "$rcfiles/bash/rc.freebsd"
fi
if [[ "$system" == 'OSX' ]]; then
	source "$rcfiles/bash/rc.osx"
fi
if [[ "$system" == 'MinGW' ]]; then
	source "$rcfiles/bash/rc.mingw"
fi

if [[ ! -n "$HOSTNAME" ]]; then
	HOSTNAME=$(hostname -s)
fi

source "$rcfiles/aliases"
source "$rcfiles/bash/completion"
source "$rcfiles/tools"

if [[ -f $HOME/.dir_colors && ( -x /usr/local/bin/dircolors || -x /usr/bin/dircolors ) ]]; then
    eval "$(dircolors $HOME/.dir_colors)"
fi

ls -A /etc/profile.d 2>/dev/null | grep '' >/dev/null
if [[ $? == 0 ]]; then
  for i in /etc/profile.d/*.sh; do
    [[ -r $i ]] && . "$i"
  done
  unset i
fi

unset rcfiles
unset system
